name: Perry

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "github.com/Andencento/Andencento"

          replace: "github.com/TheAndencento/Andencento"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'ANDENCENTO'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Perry-xD

          commit_user_email: 87893142+Perry-xD@users.noreply.github.com
